version: git.{build}

environment:
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
          ver: 2013
          generator: "Visual Studio 12 2013 Win64"
          configuration: Release
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          ver: 2015
          generator: "Visual Studio 14 2015 Win64"
          configuration: Release
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          ver: 2017
          generator: "Visual Studio 15 2017 Win64"
          configuration: Release

install:
    - git clone https://github.com/DLR-TS/SUMOLibraries
    - set SUMO_LIBRARIES=%CD%\SUMOLibraries

build_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - mkdir build_msvc%ver% &&
      cd build_msvc%ver% &&
      cmake .. -G"%generator%" -DPYTHON_EXECUTABLE=C:\Python27-x64\python.exe &&
      cmake --build . --config %configuration%

# maybe enable later but for now it probably exceeds the cache limit of 1GB
#cache:
#    - SUMOLibraries

matrix:
    fast_finish: true
